### ISSUE TITLE
Rules should match resources even when the types are expressed in a shortened way

### ISSUE THREAD

**Issue by VeraBE** [Azure/template-analyzer#163] opened 2021-07-15 19:05 UTC
Right now, if we check a property over a resource type expressed as "Microsoft.Sql/servers/auditingSettings" in the rule, it won't check on template resources where the type is expressed as "auditingSettings" because "Microsoft.Sql/servers" was previously specified

**Comment by yane3628** [comment] 2021-07-16 20:10
This is a duplicate of an issue. See https://github.com/Azure/template-analyzer/issues/115

**Closed** 2021-07-16 23:48 UTC
Labels: bug, duplicate
